{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "f9e088b4",
   "metadata": {},
   "source": [
    "Python Program to Read the Contents of a File:"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 89,
   "id": "3ae293de",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "9at Cat c9T mat bat rat hat\n",
      "abcdefghijklmnopqurtuvwxyz\n",
      "ABCDEFGHIJKLMNOPQRSTUVWXYZ\\s\n",
      "321-555-4321\n",
      "1234567890\n",
      "Ha HaHa\n",
      "MetaCharacters (Need to be escaped):\n",
      ". ^ $ * + ? { } [ ] \\ | ( )\n",
      "guptaabhishek.com\n",
      "abhishek-8765-gupta@yahoo.com\n",
      "abhi_gyupta@gamil.abc\n",
      "321-555-4321\n",
      "123.555.1234\n",
      "123*555*1234\n",
      "123.555.1234\n",
      "800-555-1234\n",
      "900-555-1234\n",
      "Mr. Schafer\n",
      "Mr Smith\n",
      "Ms Davis\n",
      "Mrs. Robinson\n",
      "Mr. T\n",
      "Mr_hello\n",
      "abhsihek.gupta@gmail.com\n",
      "abhishek-1234gupta@gmail.org\n",
      "abhishek@hotmail.net\n"
     ]
    }
   ],
   "source": [
    "f  =  open(r'C:\\Users\\tiwar\\Documents\\GitRepo\\Business-Analysis\\Python\\Assign8 Files\\new.txt','r')\n",
    "print(f.read())"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "8566f5f2",
   "metadata": {},
   "source": [
    "Python Program to Count the Number of Words in a Text File"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 88,
   "id": "b04d56fc",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "462\n"
     ]
    }
   ],
   "source": [
    "f  =  open(r'C:\\Users\\tiwar\\Documents\\GitRepo\\Business-Analysis\\Python\\Assign8 Files\\new.txt','w')\n",
    "print(f.write('''9at Cat c9T mat bat rat hat\n",
    "abcdefghijklmnopqurtuvwxyz\n",
    "ABCDEFGHIJKLMNOPQRSTUVWXYZ\\s\n",
    "321-555-4321\n",
    "1234567890\n",
    "Ha HaHa\n",
    "MetaCharacters (Need to be escaped):\n",
    ". ^ $ * + ? { } [ ] \\ | ( )\n",
    "guptaabhishek.com\n",
    "abhishek-8765-gupta@yahoo.com\n",
    "abhi_gyupta@gamil.abc\n",
    "321-555-4321\n",
    "123.555.1234\n",
    "123*555*1234\n",
    "123.555.1234\n",
    "800-555-1234\n",
    "900-555-1234\n",
    "Mr. Schafer\n",
    "Mr Smith\n",
    "Ms Davis\n",
    "Mrs. Robinson\n",
    "Mr. T\n",
    "Mr_hello\n",
    "abhsihek.gupta@gmail.com\n",
    "abhishek-1234gupta@gmail.org\n",
    "abhishek@hotmail.net'''))\n",
    "f.close()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 90,
   "id": "ed9eef45",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "['9at', 'Cat', 'c9T', 'mat', 'bat', 'rat', 'hat', 'abcdefghijklmnopqurtuvwxyz', 'ABCDEFGHIJKLMNOPQRSTUVWXYZ\\\\s', '321-555-4321', '1234567890', 'Ha', 'HaHa', 'MetaCharacters', '(Need', 'to', 'be', 'escaped):', '.', '^', '$', '*', '+', '?', '{', '}', '[', ']', '\\\\', '|', '(', ')', 'guptaabhishek.com', 'abhishek-8765-gupta@yahoo.com', 'abhi_gyupta@gamil.abc', '321-555-4321', '123.555.1234', '123*555*1234', '123.555.1234', '800-555-1234', '900-555-1234', 'Mr.', 'Schafer', 'Mr', 'Smith', 'Ms', 'Davis', 'Mrs.', 'Robinson', 'Mr.', 'T', 'Mr_hello', 'abhsihek.gupta@gmail.com', 'abhishek-1234gupta@gmail.org', 'abhishek@hotmail.net']\n",
      "55\n"
     ]
    }
   ],
   "source": [
    "num = 0\n",
    "\n",
    "with open(r'C:\\Users\\tiwar\\Documents\\GitRepo\\Business-Analysis\\Python\\Assign8 Files\\new.txt','r+') as f:\n",
    "    data = f.read()\n",
    "    \n",
    "    words = data.split()\n",
    "    print(words)\n",
    "    num = len(words)\n",
    "print(num)\n",
    "f.close()"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "f9320d23",
   "metadata": {},
   "source": [
    "Python Program to Read a String from the User and Append it\n",
    "into a File"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 91,
   "id": "e38ca64b",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Enter the String: I am Ankit\n",
      "T mat bat rat hat\n",
      "abcdefghijklmnopqurtuvwxyz\n",
      "ABCDEFGHIJKLMNOPQRSTUVWXYZ\\s\n",
      "321-555-4321\n",
      "1234567890\n",
      "Ha HaHa\n",
      "MetaCharacters (Need to be escaped):\n",
      ". ^ $ * + ? { } [ ] \\ | ( )\n",
      "guptaabhishek.com\n",
      "abhishek-8765-gupta@yahoo.com\n",
      "abhi_gyupta@gamil.abc\n",
      "321-555-4321\n",
      "123.555.1234\n",
      "123*555*1234\n",
      "123.555.1234\n",
      "800-555-1234\n",
      "900-555-1234\n",
      "Mr. Schafer\n",
      "Mr Smith\n",
      "Ms Davis\n",
      "Mrs. Robinson\n",
      "Mr. T\n",
      "Mr_hello\n",
      "abhsihek.gupta@gmail.com\n",
      "abhishek-1234gupta@gmail.org\n",
      "abhishek@hotmail.net\n"
     ]
    }
   ],
   "source": [
    "strng = input('Enter the String: ')\n",
    "\n",
    "with open(r'C:\\Users\\tiwar\\Documents\\GitRepo\\Business-Analysis\\Python\\Assign8 Files\\new.txt','r+') as f:\n",
    "    f.write(strng)\n",
    "    print(f.read())\n",
    "f.close()\n",
    "    \n",
    "    "
   ]
  },
  {
   "cell_type": "markdown",
   "id": "d620a133",
   "metadata": {},
   "source": [
    "Python Program to Copy the Contents of One File into\n",
    "Another"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 92,
   "id": "16771e1f",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "I am AnkitT mat bat rat hat\n",
      "abcdefghijklmnopqurtuvwxyz\n",
      "ABCDEFGHIJKLMNOPQRSTUVWXYZ\\s\n",
      "321-555-4321\n",
      "1234567890\n",
      "Ha HaHa\n",
      "MetaCharacters (Need to be escaped):\n",
      ". ^ $ * + ? { } [ ] \\ | ( )\n",
      "guptaabhishek.com\n",
      "abhishek-8765-gupta@yahoo.com\n",
      "abhi_gyupta@gamil.abc\n",
      "321-555-4321\n",
      "123.555.1234\n",
      "123*555*1234\n",
      "123.555.1234\n",
      "800-555-1234\n",
      "900-555-1234\n",
      "Mr. Schafer\n",
      "Mr Smith\n",
      "Ms Davis\n",
      "Mrs. Robinson\n",
      "Mr. T\n",
      "Mr_hello\n",
      "abhsihek.gupta@gmail.com\n",
      "abhishek-1234gupta@gmail.org\n",
      "abhishek@hotmail.net\n",
      "I am AnkitT mat bat rat hat\n",
      "abcdefghijklmnopqurtuvwxyz\n",
      "ABCDEFGHIJKLMNOPQRSTUVWXYZ\\s\n",
      "321-555-4321\n",
      "1234567890\n",
      "Ha HaHa\n",
      "MetaCharacters (Need to be escaped):\n",
      ". ^ $ * + ? { } [ ] \\ | ( )\n",
      "guptaabhishek.com\n",
      "abhishek-8765-gupta@yahoo.com\n",
      "abhi_gyupta@gamil.abc\n",
      "321-555-4321\n",
      "123.555.1234\n",
      "123*555*1234\n",
      "123.555.1234\n",
      "800-555-1234\n",
      "900-555-1234\n",
      "Mr. Schafer\n",
      "Mr Smith\n",
      "Ms Davis\n",
      "Mrs. Robinson\n",
      "Mr. T\n",
      "Mr_hello\n",
      "abhsihek.gupta@gmail.com\n",
      "abhishek-1234gupta@gmail.org\n",
      "abhishek@hotmail.net\n"
     ]
    }
   ],
   "source": [
    "with open(r'C:\\Users\\tiwar\\Documents\\GitRepo\\Business-Analysis\\Python\\Assign8 Files\\new.txt','r') as f:\n",
    "    data = f.read()\n",
    "    file = open(r'C:\\Users\\tiwar\\Documents\\GitRepo\\Business-Analysis\\Python\\Assign8 Files\\text.txt','w')\n",
    "    file.write(data)\n",
    "    print(data)\n",
    "    file.close()\n",
    "f.close()\n",
    "with open(r'C:\\Users\\tiwar\\Documents\\GitRepo\\Business-Analysis\\Python\\Assign8 Files\\text.txt','r') as f1:\n",
    "    print(f1.read())\n",
    "    f1.close()"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "4d0afc7e",
   "metadata": {},
   "source": [
    "Python Program that Reads a Text File and Counts the\n",
    "Number of Times a Certain Letter Appears in the Text File:"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 93,
   "id": "e934bf20",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Enter the Letter: a\n",
      "32\n"
     ]
    }
   ],
   "source": [
    "f = open(r'C:\\Users\\tiwar\\Documents\\GitRepo\\Business-Analysis\\Python\\Assign8 Files\\text.txt','r')\n",
    "data = f.read()\n",
    "\n",
    "lst = list(data)\n",
    "\n",
    "num = 0\n",
    "lettr = input('Enter the Letter: ')\n",
    "for i in lst:\n",
    "    if i == lettr:\n",
    "        num = num + 1\n",
    "    else:\n",
    "        continue\n",
    "print(num)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "97bfd25c",
   "metadata": {},
   "source": [
    "Python Program to Append the Contents of One File to\n",
    "Another File"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 105,
   "id": "beb18a75",
   "metadata": {},
   "outputs": [],
   "source": [
    "f = open(r'C:\\Users\\tiwar\\Documents\\GitRepo\\Business-Analysis\\Python\\Assign8 Files\\new.txt','r')\n",
    "data = f.read()\n",
    "\n",
    "f1 = open(r'C:\\Users\\tiwar\\Documents\\GitRepo\\Business-Analysis\\Python\\Assign8 Files\\text.txt','a+')\n",
    "f1.write('\\n' + data)\n",
    "f1.close()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 106,
   "id": "e70af77f",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "I am AnkitT mat bat rat hat\n",
      "abcdefghijklmnopqurtuvwxyz\n",
      "ABCDEFGHIJKLMNOPQRSTUVWXYZ\\s\n",
      "321-555-4321\n",
      "1234567890\n",
      "Ha HaHa\n",
      "MetaCharacters (Need to be escaped):\n",
      ". ^ $ * + ? { } [ ] \\ | ( )\n",
      "guptaabhishek.com\n",
      "abhishek-8765-gupta@yahoo.com\n",
      "abhi_gyupta@gamil.abc\n",
      "321-555-4321\n",
      "123.555.1234\n",
      "123*555*1234\n",
      "123.555.1234\n",
      "800-555-1234\n",
      "900-555-1234\n",
      "Mr. Schafer\n",
      "Mr Smith\n",
      "Ms Davis\n",
      "Mrs. Robinson\n",
      "Mr. T\n",
      "Mr_hello\n",
      "abhsihek.gupta@gmail.com\n",
      "abhishek-1234gupta@gmail.org\n",
      "abhishek@hotmail.net\n",
      "I am AnkitT mat bat rat hat\n",
      "abcdefghijklmnopqurtuvwxyz\n",
      "ABCDEFGHIJKLMNOPQRSTUVWXYZ\\s\n",
      "321-555-4321\n",
      "1234567890\n",
      "Ha HaHa\n",
      "MetaCharacters (Need to be escaped):\n",
      ". ^ $ * + ? { } [ ] \\ | ( )\n",
      "guptaabhishek.com\n",
      "abhishek-8765-gupta@yahoo.com\n",
      "abhi_gyupta@gamil.abc\n",
      "321-555-4321\n",
      "123.555.1234\n",
      "123*555*1234\n",
      "123.555.1234\n",
      "800-555-1234\n",
      "900-555-1234\n",
      "Mr. Schafer\n",
      "Mr Smith\n",
      "Ms Davis\n",
      "Mrs. Robinson\n",
      "Mr. T\n",
      "Mr_hello\n",
      "abhsihek.gupta@gmail.com\n",
      "abhishek-1234gupta@gmail.org\n",
      "abhishek@hotmail.net'\n",
      "' + data'\n",
      "' + data\n",
      "I am AnkitT mat bat rat hat\n",
      "abcdefghijklmnopqurtuvwxyz\n",
      "ABCDEFGHIJKLMNOPQRSTUVWXYZ\\s\n",
      "321-555-4321\n",
      "1234567890\n",
      "Ha HaHa\n",
      "MetaCharacters (Need to be escaped):\n",
      ". ^ $ * + ? { } [ ] \\ | ( )\n",
      "guptaabhishek.com\n",
      "abhishek-8765-gupta@yahoo.com\n",
      "abhi_gyupta@gamil.abc\n",
      "321-555-4321\n",
      "123.555.1234\n",
      "123*555*1234\n",
      "123.555.1234\n",
      "800-555-1234\n",
      "900-555-1234\n",
      "Mr. Schafer\n",
      "Mr Smith\n",
      "Ms Davis\n",
      "Mrs. Robinson\n",
      "Mr. T\n",
      "Mr_hello\n",
      "abhsihek.gupta@gmail.com\n",
      "abhishek-1234gupta@gmail.org\n",
      "abhishek@hotmail.net'\n",
      "' + data\n",
      "I am AnkitT mat bat rat hat\n",
      "abcdefghijklmnopqurtuvwxyz\n",
      "ABCDEFGHIJKLMNOPQRSTUVWXYZ\\s\n",
      "321-555-4321\n",
      "1234567890\n",
      "Ha HaHa\n",
      "MetaCharacters (Need to be escaped):\n",
      ". ^ $ * + ? { } [ ] \\ | ( )\n",
      "guptaabhishek.com\n",
      "abhishek-8765-gupta@yahoo.com\n",
      "abhi_gyupta@gamil.abc\n",
      "321-555-4321\n",
      "123.555.1234\n",
      "123*555*1234\n",
      "123.555.1234\n",
      "800-555-1234\n",
      "900-555-1234\n",
      "Mr. Schafer\n",
      "Mr Smith\n",
      "Ms Davis\n",
      "Mrs. Robinson\n",
      "Mr. T\n",
      "Mr_hello\n",
      "abhsihek.gupta@gmail.com\n",
      "abhishek-1234gupta@gmail.org\n",
      "abhishek@hotmail.net'\n",
      "' + data'\n",
      "' + data\n",
      "I am AnkitT mat bat rat hat\n",
      "abcdefghijklmnopqurtuvwxyz\n",
      "ABCDEFGHIJKLMNOPQRSTUVWXYZ\\s\n",
      "321-555-4321\n",
      "1234567890\n",
      "Ha HaHa\n",
      "MetaCharacters (Need to be escaped):\n",
      ". ^ $ * + ? { } [ ] \\ | ( )\n",
      "guptaabhishek.com\n",
      "abhishek-8765-gupta@yahoo.com\n",
      "abhi_gyupta@gamil.abc\n",
      "321-555-4321\n",
      "123.555.1234\n",
      "123*555*1234\n",
      "123.555.1234\n",
      "800-555-1234\n",
      "900-555-1234\n",
      "Mr. Schafer\n",
      "Mr Smith\n",
      "Ms Davis\n",
      "Mrs. Robinson\n",
      "Mr. T\n",
      "Mr_hello\n",
      "abhsihek.gupta@gmail.com\n",
      "abhishek-1234gupta@gmail.org\n",
      "abhishek@hotmail.net'\n",
      "' + data\n",
      "I am AnkitT mat bat rat hat\n",
      "abcdefghijklmnopqurtuvwxyz\n",
      "ABCDEFGHIJKLMNOPQRSTUVWXYZ\\s\n",
      "321-555-4321\n",
      "1234567890\n",
      "Ha HaHa\n",
      "MetaCharacters (Need to be escaped):\n",
      ". ^ $ * + ? { } [ ] \\ | ( )\n",
      "guptaabhishek.com\n",
      "abhishek-8765-gupta@yahoo.com\n",
      "abhi_gyupta@gamil.abc\n",
      "321-555-4321\n",
      "123.555.1234\n",
      "123*555*1234\n",
      "123.555.1234\n",
      "800-555-1234\n",
      "900-555-1234\n",
      "Mr. Schafer\n",
      "Mr Smith\n",
      "Ms Davis\n",
      "Mrs. Robinson\n",
      "Mr. T\n",
      "Mr_hello\n",
      "abhsihek.gupta@gmail.com\n",
      "abhishek-1234gupta@gmail.org\n",
      "abhishek@hotmail.net'\n",
      "' + data'\n",
      "' + data\n",
      "I am AnkitT mat bat rat hat\n",
      "abcdefghijklmnopqurtuvwxyz\n",
      "ABCDEFGHIJKLMNOPQRSTUVWXYZ\\s\n",
      "321-555-4321\n",
      "1234567890\n",
      "Ha HaHa\n",
      "MetaCharacters (Need to be escaped):\n",
      ". ^ $ * + ? { } [ ] \\ | ( )\n",
      "guptaabhishek.com\n",
      "abhishek-8765-gupta@yahoo.com\n",
      "abhi_gyupta@gamil.abc\n",
      "321-555-4321\n",
      "123.555.1234\n",
      "123*555*1234\n",
      "123.555.1234\n",
      "800-555-1234\n",
      "900-555-1234\n",
      "Mr. Schafer\n",
      "Mr Smith\n",
      "Ms Davis\n",
      "Mrs. Robinson\n",
      "Mr. T\n",
      "Mr_hello\n",
      "abhsihek.gupta@gmail.com\n",
      "abhishek-1234gupta@gmail.org\n",
      "abhishek@hotmail.net'\n",
      "' + data\n",
      "I am AnkitT mat bat rat hat\n",
      "abcdefghijklmnopqurtuvwxyz\n",
      "ABCDEFGHIJKLMNOPQRSTUVWXYZ\\s\n",
      "321-555-4321\n",
      "1234567890\n",
      "Ha HaHa\n",
      "MetaCharacters (Need to be escaped):\n",
      ". ^ $ * + ? { } [ ] \\ | ( )\n",
      "guptaabhishek.com\n",
      "abhishek-8765-gupta@yahoo.com\n",
      "abhi_gyupta@gamil.abc\n",
      "321-555-4321\n",
      "123.555.1234\n",
      "123*555*1234\n",
      "123.555.1234\n",
      "800-555-1234\n",
      "900-555-1234\n",
      "Mr. Schafer\n",
      "Mr Smith\n",
      "Ms Davis\n",
      "Mrs. Robinson\n",
      "Mr. T\n",
      "Mr_hello\n",
      "abhsihek.gupta@gmail.com\n",
      "abhishek-1234gupta@gmail.org\n",
      "abhishek@hotmail.net'\n",
      "' + data'\n",
      "' + data\n",
      "I am AnkitT mat bat rat hat\n",
      "abcdefghijklmnopqurtuvwxyz\n",
      "ABCDEFGHIJKLMNOPQRSTUVWXYZ\\s\n",
      "321-555-4321\n",
      "1234567890\n",
      "Ha HaHa\n",
      "MetaCharacters (Need to be escaped):\n",
      ". ^ $ * + ? { } [ ] \\ | ( )\n",
      "guptaabhishek.com\n",
      "abhishek-8765-gupta@yahoo.com\n",
      "abhi_gyupta@gamil.abc\n",
      "321-555-4321\n",
      "123.555.1234\n",
      "123*555*1234\n",
      "123.555.1234\n",
      "800-555-1234\n",
      "900-555-1234\n",
      "Mr. Schafer\n",
      "Mr Smith\n",
      "Ms Davis\n",
      "Mrs. Robinson\n",
      "Mr. T\n",
      "Mr_hello\n",
      "abhsihek.gupta@gmail.com\n",
      "abhishek-1234gupta@gmail.org\n",
      "abhishek@hotmail.net'\n",
      "' + data\n"
     ]
    }
   ],
   "source": [
    "f = open(r'C:\\Users\\tiwar\\Documents\\GitRepo\\Business-Analysis\\Python\\Assign8 Files\\text.txt','r')\n",
    "data = f.read()\n",
    "print(data)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "1b83c11a",
   "metadata": {},
   "source": [
    "Python Program to Count the Number of Blank Spaces in a\n",
    "Text File"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 107,
   "id": "ee0dae2c",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "285\n"
     ]
    }
   ],
   "source": [
    "f = open(r'C:\\Users\\tiwar\\Documents\\GitRepo\\Business-Analysis\\Python\\Assign8 Files\\text.txt','r')\n",
    "data = f.read()\n",
    "\n",
    "lst = list(data)\n",
    "\n",
    "num = 0\n",
    "lettr = ' '\n",
    "for i in lst:\n",
    "    if i == lettr:\n",
    "        num = num + 1\n",
    "    else:\n",
    "        continue\n",
    "print(num)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "497156a3",
   "metadata": {},
   "source": [
    "Python Program to Read the Contents of a File in Reverse\n",
    "Order"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 108,
   "id": "43149f8d",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "atad + '\n",
      "'ten.liamtoh@kehsihba\n",
      "gro.liamg@atpug4321-kehsihba\n",
      "moc.liamg@atpug.kehishba\n",
      "olleh_rM\n",
      "T .rM\n",
      "nosniboR .srM\n",
      "sivaD sM\n",
      "htimS rM\n",
      "refahcS .rM\n",
      "4321-555-009\n",
      "4321-555-008\n",
      "4321.555.321\n",
      "4321*555*321\n",
      "4321.555.321\n",
      "1234-555-123\n",
      "cba.limag@atpuyg_ihba\n",
      "moc.oohay@atpug-5678-kehsihba\n",
      "moc.kehsihbaatpug\n",
      ") ( | \\ ] [ } { ? + * $ ^ .\n",
      ":)depacse eb ot deeN( sretcarahCateM\n",
      "aHaH aH\n",
      "0987654321\n",
      "1234-555-123\n",
      "s\\ZYXWVUTSRQPONMLKJIHGFEDCBA\n",
      "zyxwvutruqponmlkjihgfedcba\n",
      "tah tar tab tam TtiknA ma I\n",
      "atad + '\n",
      "'atad + '\n",
      "'ten.liamtoh@kehsihba\n",
      "gro.liamg@atpug4321-kehsihba\n",
      "moc.liamg@atpug.kehishba\n",
      "olleh_rM\n",
      "T .rM\n",
      "nosniboR .srM\n",
      "sivaD sM\n",
      "htimS rM\n",
      "refahcS .rM\n",
      "4321-555-009\n",
      "4321-555-008\n",
      "4321.555.321\n",
      "4321*555*321\n",
      "4321.555.321\n",
      "1234-555-123\n",
      "cba.limag@atpuyg_ihba\n",
      "moc.oohay@atpug-5678-kehsihba\n",
      "moc.kehsihbaatpug\n",
      ") ( | \\ ] [ } { ? + * $ ^ .\n",
      ":)depacse eb ot deeN( sretcarahCateM\n",
      "aHaH aH\n",
      "0987654321\n",
      "1234-555-123\n",
      "s\\ZYXWVUTSRQPONMLKJIHGFEDCBA\n",
      "zyxwvutruqponmlkjihgfedcba\n",
      "tah tar tab tam TtiknA ma I\n",
      "atad + '\n",
      "'ten.liamtoh@kehsihba\n",
      "gro.liamg@atpug4321-kehsihba\n",
      "moc.liamg@atpug.kehishba\n",
      "olleh_rM\n",
      "T .rM\n",
      "nosniboR .srM\n",
      "sivaD sM\n",
      "htimS rM\n",
      "refahcS .rM\n",
      "4321-555-009\n",
      "4321-555-008\n",
      "4321.555.321\n",
      "4321*555*321\n",
      "4321.555.321\n",
      "1234-555-123\n",
      "cba.limag@atpuyg_ihba\n",
      "moc.oohay@atpug-5678-kehsihba\n",
      "moc.kehsihbaatpug\n",
      ") ( | \\ ] [ } { ? + * $ ^ .\n",
      ":)depacse eb ot deeN( sretcarahCateM\n",
      "aHaH aH\n",
      "0987654321\n",
      "1234-555-123\n",
      "s\\ZYXWVUTSRQPONMLKJIHGFEDCBA\n",
      "zyxwvutruqponmlkjihgfedcba\n",
      "tah tar tab tam TtiknA ma I\n",
      "atad + '\n",
      "'atad + '\n",
      "'ten.liamtoh@kehsihba\n",
      "gro.liamg@atpug4321-kehsihba\n",
      "moc.liamg@atpug.kehishba\n",
      "olleh_rM\n",
      "T .rM\n",
      "nosniboR .srM\n",
      "sivaD sM\n",
      "htimS rM\n",
      "refahcS .rM\n",
      "4321-555-009\n",
      "4321-555-008\n",
      "4321.555.321\n",
      "4321*555*321\n",
      "4321.555.321\n",
      "1234-555-123\n",
      "cba.limag@atpuyg_ihba\n",
      "moc.oohay@atpug-5678-kehsihba\n",
      "moc.kehsihbaatpug\n",
      ") ( | \\ ] [ } { ? + * $ ^ .\n",
      ":)depacse eb ot deeN( sretcarahCateM\n",
      "aHaH aH\n",
      "0987654321\n",
      "1234-555-123\n",
      "s\\ZYXWVUTSRQPONMLKJIHGFEDCBA\n",
      "zyxwvutruqponmlkjihgfedcba\n",
      "tah tar tab tam TtiknA ma I\n",
      "atad + '\n",
      "'ten.liamtoh@kehsihba\n",
      "gro.liamg@atpug4321-kehsihba\n",
      "moc.liamg@atpug.kehishba\n",
      "olleh_rM\n",
      "T .rM\n",
      "nosniboR .srM\n",
      "sivaD sM\n",
      "htimS rM\n",
      "refahcS .rM\n",
      "4321-555-009\n",
      "4321-555-008\n",
      "4321.555.321\n",
      "4321*555*321\n",
      "4321.555.321\n",
      "1234-555-123\n",
      "cba.limag@atpuyg_ihba\n",
      "moc.oohay@atpug-5678-kehsihba\n",
      "moc.kehsihbaatpug\n",
      ") ( | \\ ] [ } { ? + * $ ^ .\n",
      ":)depacse eb ot deeN( sretcarahCateM\n",
      "aHaH aH\n",
      "0987654321\n",
      "1234-555-123\n",
      "s\\ZYXWVUTSRQPONMLKJIHGFEDCBA\n",
      "zyxwvutruqponmlkjihgfedcba\n",
      "tah tar tab tam TtiknA ma I\n",
      "atad + '\n",
      "'atad + '\n",
      "'ten.liamtoh@kehsihba\n",
      "gro.liamg@atpug4321-kehsihba\n",
      "moc.liamg@atpug.kehishba\n",
      "olleh_rM\n",
      "T .rM\n",
      "nosniboR .srM\n",
      "sivaD sM\n",
      "htimS rM\n",
      "refahcS .rM\n",
      "4321-555-009\n",
      "4321-555-008\n",
      "4321.555.321\n",
      "4321*555*321\n",
      "4321.555.321\n",
      "1234-555-123\n",
      "cba.limag@atpuyg_ihba\n",
      "moc.oohay@atpug-5678-kehsihba\n",
      "moc.kehsihbaatpug\n",
      ") ( | \\ ] [ } { ? + * $ ^ .\n",
      ":)depacse eb ot deeN( sretcarahCateM\n",
      "aHaH aH\n",
      "0987654321\n",
      "1234-555-123\n",
      "s\\ZYXWVUTSRQPONMLKJIHGFEDCBA\n",
      "zyxwvutruqponmlkjihgfedcba\n",
      "tah tar tab tam TtiknA ma I\n",
      "atad + '\n",
      "'ten.liamtoh@kehsihba\n",
      "gro.liamg@atpug4321-kehsihba\n",
      "moc.liamg@atpug.kehishba\n",
      "olleh_rM\n",
      "T .rM\n",
      "nosniboR .srM\n",
      "sivaD sM\n",
      "htimS rM\n",
      "refahcS .rM\n",
      "4321-555-009\n",
      "4321-555-008\n",
      "4321.555.321\n",
      "4321*555*321\n",
      "4321.555.321\n",
      "1234-555-123\n",
      "cba.limag@atpuyg_ihba\n",
      "moc.oohay@atpug-5678-kehsihba\n",
      "moc.kehsihbaatpug\n",
      ") ( | \\ ] [ } { ? + * $ ^ .\n",
      ":)depacse eb ot deeN( sretcarahCateM\n",
      "aHaH aH\n",
      "0987654321\n",
      "1234-555-123\n",
      "s\\ZYXWVUTSRQPONMLKJIHGFEDCBA\n",
      "zyxwvutruqponmlkjihgfedcba\n",
      "tah tar tab tam TtiknA ma I\n",
      "atad + '\n",
      "'atad + '\n",
      "'ten.liamtoh@kehsihba\n",
      "gro.liamg@atpug4321-kehsihba\n",
      "moc.liamg@atpug.kehishba\n",
      "olleh_rM\n",
      "T .rM\n",
      "nosniboR .srM\n",
      "sivaD sM\n",
      "htimS rM\n",
      "refahcS .rM\n",
      "4321-555-009\n",
      "4321-555-008\n",
      "4321.555.321\n",
      "4321*555*321\n",
      "4321.555.321\n",
      "1234-555-123\n",
      "cba.limag@atpuyg_ihba\n",
      "moc.oohay@atpug-5678-kehsihba\n",
      "moc.kehsihbaatpug\n",
      ") ( | \\ ] [ } { ? + * $ ^ .\n",
      ":)depacse eb ot deeN( sretcarahCateM\n",
      "aHaH aH\n",
      "0987654321\n",
      "1234-555-123\n",
      "s\\ZYXWVUTSRQPONMLKJIHGFEDCBA\n",
      "zyxwvutruqponmlkjihgfedcba\n",
      "tah tar tab tam TtiknA ma I\n",
      "ten.liamtoh@kehsihba\n",
      "gro.liamg@atpug4321-kehsihba\n",
      "moc.liamg@atpug.kehishba\n",
      "olleh_rM\n",
      "T .rM\n",
      "nosniboR .srM\n",
      "sivaD sM\n",
      "htimS rM\n",
      "refahcS .rM\n",
      "4321-555-009\n",
      "4321-555-008\n",
      "4321.555.321\n",
      "4321*555*321\n",
      "4321.555.321\n",
      "1234-555-123\n",
      "cba.limag@atpuyg_ihba\n",
      "moc.oohay@atpug-5678-kehsihba\n",
      "moc.kehsihbaatpug\n",
      ") ( | \\ ] [ } { ? + * $ ^ .\n",
      ":)depacse eb ot deeN( sretcarahCateM\n",
      "aHaH aH\n",
      "0987654321\n",
      "1234-555-123\n",
      "s\\ZYXWVUTSRQPONMLKJIHGFEDCBA\n",
      "zyxwvutruqponmlkjihgfedcba\n",
      "tah tar tab tam TtiknA ma \n"
     ]
    }
   ],
   "source": [
    "f = open(r'C:\\Users\\tiwar\\Documents\\GitRepo\\Business-Analysis\\Python\\Assign8 Files\\text.txt','r')\n",
    "data = f.read()\n",
    "print(data[-1:-len(data):-1])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 123,
   "id": "360356f1",
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Enter the Path: C:\\Users\\tiwar\\Documents\\GitRepo\\Business-Analysis\\Python\\Assign8 Files\\text.txt\n",
      "A boy is playing there.\n",
      "\n",
      "There is a playground.\n",
      "\n",
      "An aeroplane is in the sky.\n",
      "\n",
      "The sky is pink.\n",
      "\n",
      "Alphabets and numbers are allowed in the password.\n"
     ]
    }
   ],
   "source": [
    "# Write a function in python to read the content from \n",
    "# a text file \"poem.txt\" line by line and display the same on screen.\n",
    "\n",
    "\n",
    "def readPoem(a):\n",
    "    f = open(a,'r')\n",
    "    for lines in f:\n",
    "        print(lines)\n",
    "        continue\n",
    "\n",
    "strng = input('Enter the Path: ')\n",
    "readPoem(strng)\n",
    "f.close()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 132,
   "id": "02e5e547",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Enter the Path: C:\\Users\\tiwar\\Documents\\GitRepo\\Business-Analysis\\Python\\Assign8 Files\\text.txt\n",
      "3\n"
     ]
    }
   ],
   "source": [
    "# Write a function in python to count the number of lines \n",
    "# from a text file \"story.txt\" which is not starting with an alphabet \"T\". \n",
    "\n",
    "# Example: If the file \"story.txt\" contains the following lines: A boy is playing there.\n",
    "# There is a playground.\n",
    "# An aeroplane is in the sky.\n",
    "# The sky is pink.\n",
    "# Alphabets and numbers are allowed in the password.\n",
    "# The function should display the output as 3\n",
    "\n",
    "import re\n",
    "\n",
    "pattern = r'[^T][.]*'\n",
    "\n",
    "def funStory(a):\n",
    "    num = 0\n",
    "    f = open(a,'r')\n",
    "    for lines in f:\n",
    "        if bool(re.match(pattern,lines))== True:\n",
    "            num = num + 1\n",
    "        else:\n",
    "            continue\n",
    "    print(num)\n",
    "\n",
    "strng = input('Enter the Path: ')\n",
    "funStory(strng)\n",
    "f.close()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ab0b40ef",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Write a function in Python to count and display the total number of words in a text file.\n",
    "\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
